import dilations_extensions_compressions_linear_operators_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dilations_extensions_compressions_linear_operators_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dilations_extensions_compressions_linear_operators_lemma_canonical_lane_mathlib
end HautevilleHouse
